### ISSUE TITLE
Allow MongoDB Objects such as ObjectId()

### ISSUE THREAD

**Issue by Sammaye** [angelozerr/mongo-mapreduce-webbrowser#14]
Noticed that ObjectId() doesn't work:

```
{'_id':ObjectId('d')}
```

mainly because it filters to Java.

Would be cool to put a mapping between Java objects and console objects. Will need some work to make objectId() create a new object of its self but should work.

**Comment by angelozerr** [comment]
If you read https://github.com/angelozerr/mongo-mapreduce-webbrowser/wiki/Writing-MapReduce you can see that BSON document should be filled with strict mode (http://docs.mongodb.org/manual/reference/mongodb-extended-json/) :

---

[{"_id":{"$oid":"50d8fdedadd222278ba9090f"},"date":{"$date":"2012-12-25T01:14:21.312Z"},"url":"http;//iiiiiiiiiii"},

## ...

I use JSON parser to load the BSON document, I don't know if it is able to load javascript object.

**Comment by Sammaye** [comment]
Aha I didn't see that bit stupid me, does it convert the console documents down? A lot of people will paste from console so it might be kool if the input box could strip these objects and replace them with the compatible edition

**Comment by angelozerr** [comment]
I will see if it's possible.

But my idea is to provide the capability to load BSON document from MongoDB directly.

See issue at https://github.com/angelozerr/mongo-mapreduce-webbrowser/issues/3

**Comment by Sammaye** [comment]
Yeah that could work as well provided you give the ability to query with the same complexity as the console
